// <auto-generated />
using System;
using AtlasAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtlasAPI.Migrations
{
    [DbContext(typeof(ContextoAtlas))]
    partial class ContextoAtlasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AtlasAPI.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CategoriaIconoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<int>("MapaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MapaId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("AtlasAPI.Models.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("AtlasAPI.Models.Mapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioReferencia")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Leyenda")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlGeoJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mapas");
                });

            modelBuilder.Entity("AtlasAPI.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aciertos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalPreguntas")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("AtlasAPI.Models.PreguntaQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Explicacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpcionA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpcionB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpcionC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RespuestaCorrecta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Siglo")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("AtlasAPI.Models.RespuestaPartida", b =>
                {
                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsAcertada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RespuestaSeleccionada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PartidaId", "PreguntaId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("RespuestasPartida");
                });

            modelBuilder.Entity("AtlasAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaBaneado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AtlasAPI.Models.UsuarioEventoFavorito", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGuardado")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "EventoId");

                    b.HasIndex("EventoId");

                    b.ToTable("UsuarioEventoFavoritos");
                });

            modelBuilder.Entity("AtlasAPI.Models.UsuarioLogro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LogroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosLogros");
                });

            modelBuilder.Entity("AtlasAPI.Models.Evento", b =>
                {
                    b.HasOne("AtlasAPI.Models.Mapa", "Mapa")
                        .WithMany("Eventos")
                        .HasForeignKey("MapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapa");
                });

            modelBuilder.Entity("AtlasAPI.Models.Logro", b =>
                {
                    b.HasOne("AtlasAPI.Models.Usuario", null)
                        .WithMany("Logros")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("AtlasAPI.Models.RespuestaPartida", b =>
                {
                    b.HasOne("AtlasAPI.Models.Partida", "Partida")
                        .WithMany("RespuestasPartida")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtlasAPI.Models.PreguntaQuiz", "Pregunta")
                        .WithMany("RespuestasPartida")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("AtlasAPI.Models.UsuarioEventoFavorito", b =>
                {
                    b.HasOne("AtlasAPI.Models.Evento", "Evento")
                        .WithMany("UsuariosFavoritos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtlasAPI.Models.Usuario", "Usuario")
                        .WithMany("EventosFavoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasAPI.Models.UsuarioLogro", b =>
                {
                    b.HasOne("AtlasAPI.Models.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtlasAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtlasAPI.Models.Evento", b =>
                {
                    b.Navigation("UsuariosFavoritos");
                });

            modelBuilder.Entity("AtlasAPI.Models.Mapa", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("AtlasAPI.Models.Partida", b =>
                {
                    b.Navigation("RespuestasPartida");
                });

            modelBuilder.Entity("AtlasAPI.Models.PreguntaQuiz", b =>
                {
                    b.Navigation("RespuestasPartida");
                });

            modelBuilder.Entity("AtlasAPI.Models.Usuario", b =>
                {
                    b.Navigation("EventosFavoritos");

                    b.Navigation("Logros");
                });
#pragma warning restore 612, 618
        }
    }
}
